'use strict';

// data/history.json + out/*.json -> the LuaLS meta file that IS the reference.
//
//   node gen-meta.js                 write out/uix-callbacks.lua, a preview
//   node gen-meta.js --site          write the reference itself, one directory up
//
// The version axis comes from the history, which covers every UIX release from
// 8.0.0.1 ("8.0.0.1-beta") onwards; lib/axis.js turns it into Since, Versions and
// Removed. Those three keys are GENERATED - recomputed in full on every run -
// because the history can now prove them. What is carried across untouched is the
// authored half: the `---` prose and the text trailing a ---@param / ---@return.
//
// Each hook's detail - arguments, call sites, aggregation - comes from the newest
// release that still dispatches it, which for all but two is the newest release.

const fs = require('fs');
const path = require('path');
const M = require('../meta.js');
const R = require('./lib/releases');
const H = require('./lib/history');
const A = require('./lib/axis');

const SITE = path.join(__dirname, '..');
const OUT = path.join(__dirname, 'out');

function main() {
  const toSite = process.argv.includes('--site');

  const history = H.read();
  const releases = H.releasesOf(history);
  if (!releases.length) { console.error('data/history.json is empty - run build-history.js first'); process.exit(2); }
  // Since and Versions are only true relative to the scan behind them. A history
  // that has lost its floor would silently restamp `pre-8.0` hooks with a number.
  if (releases[0].tag !== R.FLOOR) {
    console.error(`history starts at ${releases[0].tag}, not the ${R.FLOOR} floor - rebuild it with build-history.js --all`);
    process.exit(2);
  }

  const axis = A.axisOf(history);
  const present = H.presenceOf(history);

  // The releases whose full extraction is needed, and the detail they carry.
  const cover = H.coverSet(history);
  const detail = new Map();
  for (const tag of cover) {
    const f = path.join(OUT, tag + '.json');
    if (!fs.existsSync(f)) { console.error(`out/${tag}.json is missing - run build-history.js to re-extract the cover set`); process.exit(2); }
    for (const c of JSON.parse(fs.readFileSync(f, 'utf8')).callbacks) detail.set(c.menu + '::' + c.name, { tag, c });
  }

  const dest = toSite ? path.join(SITE, 'uix-callbacks.lua') : path.join(OUT, 'uix-callbacks.lua');
  // The site copy is the reference and owns the authored half, so a preview run
  // reads it too: out/uix-callbacks.lua can then never be the more current one.
  const siteFile = path.join(SITE, 'uix-callbacks.lua');
  const src = fs.existsSync(siteFile) ? siteFile : dest;
  const authored = fs.existsSync(src) ? M.authoredFrom(fs.readFileSync(src, 'utf8')) : new Map();

  // Every hook the axis has ever seen, with the tags that dispatch it.
  const seen = new Map();
  for (const r of releases) {
    for (const k of present.get(r.tag).keys) {
      if (!seen.has(k)) seen.set(k, new Set());
      seen.get(k).add(r.tag);
    }
  }

  const byMenu = new Map();
  let carried = 0, lost = [];

  for (const key of [...seen.keys()].sort()) {
    const d = detail.get(key);
    if (!d) { lost.push(key); continue; }
    const c = d.c;
    const site = c.sites[0];
    const keys = A.keysFor(axis, seen.get(key));

    const a = authored.get(key);
    if (a && (a.prose || []).length) carried++;

    const entry = {
      menu: c.menu, name: c.name, addon: c.addon, holder: c.holder, menuName: c.menuName,
      func: site.func, kind: site.kind, aggregation: site.aggregation,
      args: site.args, targets: site.targets, returnFields: site.returnFields,
      attribution: c.sites.map((s) => s.attribution).find(Boolean) || null,
      since: keys.since, versions: keys.versions, removed: keys.removed,
      // The sites are the ones in the release the detail came from, so a reader
      // opening that release finds them at those lines.
      seenAt: c.sites.map((s) => `${path.basename(s.file)}:${s.dispatchLine}`).join(' + ') + ` (${d.tag})`,
    };
    if (!byMenu.has(c.menu)) byMenu.set(c.menu, []);
    byMenu.get(c.menu).push({ name: c.name, text: M.emitEntry(entry, a), entry });
  }

  if (lost.length) { console.error('no extraction covers:', lost.join(', ')); process.exit(1); }
  for (const list of byMenu.values()) list.sort((x, y) => x.name.localeCompare(y.name));

  const head = releases[releases.length - 1].tag;
  const lineHeads = Object.entries(axis.lines).map(([l, t]) => `${t[t.length - 1]} (${l})`).join(' and ');
  const header = [
    '-- X4: Foundations - UI Extensions and HUD (UIX) callbacks reference',
    '--',
    `-- Generated by src/uix-callbacks/extract/gen-meta.js from ${R.REPO}, every`,
    `-- release from ${R.FLOOR} ("${releases[0].name}", ${releases[0].published}) to ${head}`,
    `-- inclusive: ${releases.length} releases. The current ones are ${lineHeads}.`,
    '--',
    '-- The `-- Key: value` lines and the function declarations are rewritten on every',
    '-- run. The `---` prose and the text after each ---@param / ---@return are written',
    '-- by hand and carried across untouched: edit those, and only those.',
    '--',
    '-- `Since:` is the first release that dispatches the hook. `pre-8.0` means it was',
    '-- already there in the oldest release covered. The 8.x and 9.x lines run in',
    '-- parallel, so where they differ both are given.',
    '--',
    '-- Callback names are not unique - `cleanup` is dispatched in ten menus - so every',
    '-- entry is keyed by (menu, name) and the file is one table per menu.',
    '--',
    '-- Register against these from a mod with Helper.registerCallback(name, fn, id) in',
    '-- a Helper hook, or menu.registerCallback(name, fn, id) in a menu hook.',
  ].join('\n');

  const text = M.emit(byMenu, header);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, text);

  // Round-trip: the file must read back as what was written, or the parser and the
  // writer disagree and an authored half would be lost on the next run.
  const back = M.parse(text);
  let n = 0; const bad = [];
  for (const [menu, entries] of back) {
    for (const got of entries) {
      n++;
      const want = (byMenu.get(menu) || []).find((x) => x.name === got.name);
      if (!want) { bad.push(`${menu}::${got.name} parsed but not emitted`); continue; }
      const wantNames = M.uniqueNames(want.entry.args);
      if (got.args.join(',') !== wantNames.join(',')) bad.push(`${menu}::${got.name} args ${got.args.join(',')} != ${wantNames.join(',')}`);
      if ((got.keys.Since || '') !== want.entry.since) bad.push(`${menu}::${got.name} Since drift`);
    }
  }
  const emitted = [...byMenu.values()].reduce((s, v) => s + v.length, 0);
  if (n !== emitted) bad.push(`parsed ${n} of ${emitted} entries`);

  if (bad.length) {
    console.error('ROUND-TRIP FAILED, file written but do not trust it:');
    bad.slice(0, 20).forEach((b) => console.error('  ' + b));
    process.exit(1);
  }

  const meta = {
    generated: new Date().toISOString().slice(0, 10),
    repo: history.repo,
    floor: R.FLOOR,
    floorLabel: R.FLOOR_LABEL,
    lines: Object.fromEntries(Object.entries(axis.lines).map(([l, t]) => [l, { releases: t, head: t[t.length - 1] }])),
    versions: releases.map((r) => ({
      version: r.tag, line: R.lineOf(r.tag), name: r.name, published: r.published,
      prerelease: r.prerelease, source: `${history.repo}@${r.tag}`, counts: r.counts,
    })),
    callbacks: emitted,
    menus: byMenu.size,
    cover,
  };
  const metaDest = toSite ? path.join(SITE, 'data', 'meta.json') : path.join(OUT, 'meta.json');
  fs.mkdirSync(path.dirname(metaDest), { recursive: true });
  fs.writeFileSync(metaDest, JSON.stringify(meta, null, 1));

  const bySince = new Map();
  for (const list of byMenu.values()) for (const e of list) bySince.set(e.entry.since, (bySince.get(e.entry.since) || 0) + 1);

  console.log(`${emitted} callbacks in ${byMenu.size} menus -> ${path.relative(process.cwd(), dest)}`);
  console.log(`  axis:       ${releases.length} releases, ${R.FLOOR} to ${head}; heads ${lineHeads}`);
  console.log(`  detail:     from ${cover.join(', ')}`);
  console.log(`  prose:      ${carried} of ${emitted} entries carry an authored description`);
  console.log(`  round-trip: all ${n} entries parsed back identical`);
  console.log(`  Since:      ${[...bySince].sort((a, b) => b[1] - a[1]).slice(0, 8).map(([s, k]) => `${s} x${k}`).join(', ')}`);
  const gone = [...byMenu.values()].flat().filter((e) => e.entry.removed);
  console.log(`  removed:    ${gone.length}${gone.length ? ' (' + gone.map((e) => e.entry.menu + '::' + e.entry.name).join(', ') + ')' : ''}`);
}

main();
